data:extend({
    {
        type = "item-subgroup",
        name = "crash-site",
        group = "production",
        order = "x",
    },
    {
        type = "item",
        name = "crash-site-lab",
        icon = "__atan-crash-site__/graphics/icons/crash-site-lab.png",
        icon_size = 64,
        icon_mipmaps = 4,
        subgroup = "crash-site",
        order = "x[crash-site-lab]",
        place_result = "crash-site-lab",
        stack_size = 1,
        flags = { "hidden" },
    },
    {
        type = "item",
        name = "crash-site-assembling-machine-1",
        icon = "__atan-crash-site__/graphics/icons/crash-site-assembling-machine-1.png",
        icon_size = 64,
        icon_mipmaps = 4,
        subgroup = "crash-site",
        order = "x[crash-site-assembling-machine-1]",
        place_result = "crash-site-assembling-machine-1",
        stack_size = 1,
        flags = { "hidden" },
    },
    {
        type = "item",
        name = "crash-site-assembling-machine-2",
        icon = "__atan-crash-site__/graphics/icons/crash-site-assembling-machine-2.png",
        icon_size = 64,
        icon_mipmaps = 4,
        subgroup = "crash-site",
        order = "x[crash-site-assembling-machine-2]",
        place_result = "crash-site-assembling-machine-2",
        stack_size = 1,
        flags = { "hidden" },
    },
    {
        type = "item",
        name = "crash-site-generator",
        icon = "__atan-crash-site__/graphics/icons/crash-site-generator.png",
        icon_size = 64,
        icon_mipmaps = 4,
        subgroup = "crash-site",
        order = "x[crash-site-generator]",
        place_result = "crash-site-generator",
        stack_size = 1,
        flags = { "hidden" },
    },
})
