require("prototype.assembling_machines")
require("prototype.compatability")
require("prototype.containers")
require("prototype.electric_pole")
require("prototype.generator")
require("prototype.icon")
require("prototype.items")
require("prototype.lab")
