require("prototype.assembling_machines")
require("prototype.compatibility")
require("prototype.containers")
require("prototype.generator")
require("prototype.icon")
require("prototype.items")
require("prototype.lab")
